<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Service Plan</title>
		<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot']; ?>/interface/themes/style_oemr.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory ?>/forms/TCMAssessment/style.css">
		<script type="text/javascript" src="<?php echo $GLOBALS['webroot']; ?>/library/js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlanSubModels.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlan.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlanViewModel.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				ServicePlanVM = new ServicePlanViewModel;
				ServicePlanVM.Load({
					AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/ajax.php',
					WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
					ExitUri: '<?php echo $GLOBALS['form_exit_url']; ?>',
					ServicePlanId: '<?php echo $this->servicePlanId; ?>',
					TestMode: false
				});
				ko.applyBindings(ServicePlanVM);
			});
		</script>
		<style>
			th, td { padding: 0.25em; }
			.honorlinebreak { white-space: pre-wrap }
			.innertable th { text-align: left }
		</style>
	</head>
	<body class="bgcolor2">
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div id="hoverMenu">
			<div>
				<div class="css_button" data-bind="click: Exit"><span>Cancel</span></div>
				<div class="css_button" data-bind="click: Print"><span>Print</span></div>
			</div>
		</div>
		<div class="contentWraper">
			<h1>Targeted Case Management Service Plan</h1>
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>			
			
			<div class="form-section">
				<table>
					<tbody>
						<tr>
							<th>Service Plan Type</th>
							<td colspan="3" data-bind="text: ServicePlan.TypeDisplay"></td>
						</tr>
						<tr>
							<th style="width: 25%">Clients Name</th>
							<td style="width: 25%" data-bind="text: ServicePlan.ClientName"></td>
							<th style="width: 25%">Date of Birth</th>
							<td style="width: 25%" data-bind="text: ServicePlan.ClientBirth"></td>
						</tr>
						<tr>
							<th>Medicaid #</th>
							<td data-bind="text: ServicePlan.MedicaidId"></td>
							<td colspan="2"></td>
						</tr>
						<tr>
							<th>Targeted Case Manager</th>
							<td data-bind="text: ServicePlan.CaseManagerName"></td>
							<th>Supervisor</th>
							<td data-bind="text: ServicePlan.CaseManagerSupervisorName"></td>
						</tr>
						<tr>
							<th>Written Date</th>
							<td data-bind="text: ServicePlan.DateWritten"></td>
							<th>Completion Date</th>
							<td data-bind="text: ServicePlan.DateComplete"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Diagnosis</span>
							</th>
						</tr>
						<tr data-bind="visible: ServicePlan.DiagnosisActive().length > 0" class="innertable">
							<th><span data-bind="if: ServicePlan.HasAxis">Axis</span></th>
							<th>Code</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: ServicePlan.Diagnosis">
						<tr>
							<td data-bind="text: AxisDisplay()"></td>
							<td data-bind="text: Code"></td>
							<td data-bind="text: Description"></td>
						</tr>
					</tbody>
					<tfoot>
						<tr data-bind="if: ServicePlan.DiagnosisCgas() > 0">
							<th colspan="2">
								<span>CGAS/GAS</span>
							</th>							
							<td><span data-bind="text: ServicePlan.DiagnosisCgas"></span></td>							
						</tr>
					
						<tr>
							<th colspan="2">
								Source of Diagnosis
							</th>
							<td style="width: 75%" data-bind="text: ServicePlan.DiagnosisSource"></td>
						</tr>
						
						<tr data-bind="if: ServicePlan.DiagnosisAgent() > ''">
							<th colspan="2">
								Agent
							</th>
							<td style="width: 75%" data-bind="text: ServicePlan.DiagnosisAgent"></td>
						</tr>
						
					</tfoot>
				</table>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th><span class="section-title">Current Service Needs</span></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="pre-wrap" data-bind="text: ServicePlan.CurrentServiceNeeds"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<h1>Goals/Objectives</h1>
			<div data-bind="foreach: ServicePlan.Problems">
				<div class="form-section">
					<table>
						<thead>
							<tr>
								<th style="width: 16%;">Functional Area</th>
								<td data-bind="text: Area"></td>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th>Problem</th>
								<td data-bind="text: Problem" class="honorlinebreak"></td>
							</tr>
						</tbody>
					</table>
					<div class="sourcesLink">
						<table>
							<thead>
								<tr>
									<th colspan="2" style="text-align: center; width: 100%;">Goals &amp; Objectives</th>
								</tr>
							</thead>
							<tbody data-bind="foreach: Goals">
								<tr>
									<th style="width: 16%;">Goal</th>
									<td data-bind="text: Goal" class="honorlinebreak"></td>
								</tr>
								<tr>
									<td colspan="2">
										<div class="sourcesLink" style="margin: 5px;">
											<table>
												<thead>
													<tr>
														<th colspan="3" style="text-align: center;">Objectives</th>
													</tr>
												</thead>
												<tbody data-bind="foreach: Objectives">
													<tr>
														<td rowspan="3" style="width: 60%;" data-bind="text: Objective" class="honorlinebreak"></td>
														<th>Target Date</th>
														<td style="width: 20%;" data-bind="text: TargetDate"></td>
													</tr>
													<tr>
														<th>Status</th>
														<td data-bind="text: StatusDisplay()"></td>
													</tr>
													<tr>
														<th>Progress Rating</th>
														<td data-bind="text: ProgressRate"></td>
													</tr>
												</tbody>
											</table>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<table>
						<tbody>
							<tr>
								<th style="width: 16%;">Activities</th>
								<td data-bind="text: Activities" class="honorlinebreak"></td>
							</tr>
						</tbody>
					</table>
					<div class="sourcesLink">
						<table>
							<thead>
								<tr>
									<th colspan="3" style="text-align: center;">Agency / Agent Responsible</th>
								</tr>
								<tr data-bind="visible: AgentsActive().length > 0" class="innertable">
									<th>Type</th>
									<th>Agency</th>
									<th>Agent</th>
								</tr>
							</thead>
							<tbody data-bind="foreach: Agents">
								<tr>
									<td data-bind="text: TypeDisplay()"></td>
									<td data-bind="text: Agency"></td>
									<td data-bind="text: Agent"></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th>Discharge Plan</th>
						</tr>
					</thead>
					<tbody>
						<tr><td><span data-bind="text: ServicePlan.DischargePlan" style="white-space: pre-wrap"></span></td></tr>
					</tbody>
				</table>
			</div>
			<div class="printOnly pageBreak"></div>
			<h2 class="printOnly">ATTESTATION STATEMENT</h2>
			<div class="printOnly form-section">
				<p>By signing below, I attest that I have participated in the development of the service plan, that it accurately identifies my needs and I am willing to address the goals/objectives outlined above. I further understand that the effectiveness of this service plan will be monitored regularly to assess progress and ensure that it continues to meet my needs.  I have reviewed and understand the information contained in the service plan (including diagnosis, goals/objectives and discharge plan) and have been given a copy of the service plan.</p>
			</div>
			<div class="printOnly">
				<table style="width: 100%;">
					<tr>
						<td style="width: 83%; border-bottom: 1px solid black;"></td>
<!-- Andres was here				<td style="width: 41%; border-bottom: 1px solid black;"></td>-->                                                
						<td style="width: 1%; height: 3em;"></td>
<!--    Andres was here				<td style="width: 41%; border-bottom: 1px solid black;"></td>
						<td style="width: 1%;"></td>-->
						<td style="width: 16%; border-bottom: 1px solid black;"></td>
					</tr>
					<tr>
<!--	Andres was here 			<td>Signature</td>
						<td></td>                            
                                 		<td>Client</td>-->
                                                <td><span>Client:  </span><span data-bind="text: ServicePlan.ClientName"></span></td>
						<td></td>
						<td>Date</td>
					</tr>
					<tr>
						<td style="border-bottom: 1px solid black;"></td>
						<td style="height: 3em;"></td>
						<td style="border-bottom: 1px solid black;"></td>
<!-- Andres was here                            <td></td>
						<td style="border-bottom: 1px solid black;"></td>-->
					</tr>
					<tr>
<!-- Andres was here      			<td>Signature</td>
						<td></td>-->
                                                <td><span>Legal Guardian / Parent:</span></td>
						<td></td>
						<td>Date</td>
					</tr>
					<tr>
						<td style="border-bottom: 1px solid black;"></td>
						<td style="height: 3em;"></td>
						<td style="border-bottom: 1px solid black;"></td>
<!-- Andres was here				<td></td>
						<td style="border-bottom: 1px solid black;"></td>-->
					</tr>
					<tr>
<!-- Andres was here				<td>Signature</td>
						<td></td>-->
                                                <td><span>Legal Guardian / Parent:</span></td>
						<td></td>
						<td>Date</td>
					</tr>
					<tr>
						<td style="border-bottom: 1px solid black;"></td>
						<td style="height: 3em;"></td>
						<td style="border-bottom: 1px solid black;"></td>
<!-- Andres was here				<td></td>
						<td style="border-bottom: 1px solid black;"></td>-->
					</tr>
					<tr>
<!-- Andres was here				<td>Signature</td>
						<td></td>-->
                                                <td><span>Targeted Case Manager:  </span><span data-bind="text: ServicePlan.CaseManagerName"></span></td>
                                                <td></td>
						<td>Date</td>
					</tr>
					<tr>
						<td style="border-bottom: 1px solid black;"></td>
						<td style="height: 3em;"></td>
						<td style="border-bottom: 1px solid black;"></td>
<!-- Andres was here				<td></td>
						<td style="border-bottom: 1px solid black;"></td>-->
					</tr>
					<tr>
<!-- Andres was here				<td>Signature</td>
						<td></td>-->
						<td><span>Targeted Case Manager Supervisor:  </span>	<span data-bind="text: ServicePlan.CaseManagerSupervisorName"></span></td>
						<td></td>
						<td>Date</td>
					</tr>
				</table>
			</div>
		</div>
	</body>
</html>