<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Notes</title>

		<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot']; ?>/interface/themes/style_oemr.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory ?>/forms/TCMAssessment/style.css">
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/modernizr-custom-2.6.2.js"></script>
		<script type="text/javascript">
			Modernizr.load({
				test: Modernizr.inputtypes.date,
				nope: [
					'<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-ui-1.8.21.custom.min.js',
					'<?php echo $GLOBALS['webroot']; ?>/library/css/jquery-ui-1.8.21.custom.css'
				],
				both : [
					'<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-1.9.1.min.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMNote/js/NoteSubModels.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMNote/js/Note.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMNote/js/NoteViewModel.js'
				],
				complete: function () {
					$(document).ready(function() {
						if (typeof jQuery.ui !== 'undefined') {
							$('input[type=date]').datepicker({
								dateFormat: 'yyyy-mm-dd'
							}); 
						}

						NoteVM = new NoteViewModel;
						NoteVM.Load({
							AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMNote/ajax.php',
							WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
							ExitUri: '<?php echo $GLOBALS['form_exit_url']; ?>',
							NoteId: '<?php echo $this->noteId; ?>',
							TestMode: false
						});
						ko.applyBindings(NoteVM);
					});
				}
			});
		</script>
    <style>
        table { /* override OEMR style so activity table prints nicely */
          text-align: left;
        }
    </style>    
	</head>
	<body class="bgcolor2">
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div id="hoverMenu">
			<div>
				<div class="css_button" data-bind="click: Exit"><span>Cancel</span></div>
				<div class="css_button" data-bind="click: Print"><span>Print</span></div>
			</div>
		</div>
			<div id="managerNotes" data-bind="visible: Note.ManagerNoteVisible">
				<div>
					<textarea data-bind="value: Note.ManagerNote"></textarea>
				</div>
			</div>
			<div id="finalize" data-bind="visible: Note.Finalized.Visible">
				<div>
					<div>
						<table>
							<tbody>
								<tr>
									<th>Finalized</th>
									<td>
										<div data-bind="visible: Note.Finalized.DisplayFinalize">Not Finalized</div>
										<div data-bind="visible: Note.Finalized.DisplayRevert, text: Note.Finalized.Finalized"></div>
									</td>
									<td>
										<div style="float: right; width: 16ex;" data-bind="visible: Note.Finalized.DisplayFinalize">
											<div class="css_button" data-bind="click: Finalize"><span>Finalize Service Plan</span></div>
										</div>
										<div style="float: right; width: 15ex;" data-bind="visible: Note.Finalized.DisplayRevert">
											<div class="css_button" data-bind="click: Unfinalize"><span>Revert Finalization</span></div>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div style="clear: both;"></div>
				</div>
			</div>
		</div>

		<div class="contentWraper">
			<h1>Targeted Case Management Notes</h1>
      
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>
 			<div class="form-section">
				<table>
					<tbody>
						<tr>
							<th style="width: 25%">Client Name&nbsp;</th>
							<td style="width: 25%" data-bind="text: Note.ClientName"></td>
						</tr>
            <tr><td><br></td></tr>
						<tr>
							<th>Most Recent Service Plan Date&nbsp;</th>
							<td data-bind="text: Note.DateWritten"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="6">
								<span class="section-title">Activities</span>
							</th>
						</tr>
						<tr>
							<th>Start Time</th>
							<th>End Time</th>
							<th>Minutes</th>
							<th>Activity Type</th>
							<th>Summary of Activity</th>
						</tr>
            <tr><td colspan="5"><hr></td></tr>
					</thead>
					<tbody data-bind="foreach: Note.Activities" >
 						<tr style="vertical-align: top; margin-bottom: 2em; background: rgba(255, 0, 0, 0.1);"">
              <td style="width: 8em" ><span data-bind="text: StartTime"></span></td>
							<td style="width: 8em" data-bind="text: EndTime"></td>
              <td style="text-align: right;" data-bind="text: DurationMins, style: { background: (DurationMins() < 0 || DurationMins() > 360) ? 'tomato' : ''}"></td>
							<td>&nbsp;&nbsp;<span data-bind="text: ActivityLabelDisplay()"></span></td>
              <td rowspan="2"><textarea style="height: 3.5em; border: 0; background: transparent" data-bind="value: Description, disable: true"></textarea></td>
						</tr>
            <tr style="background: rgba(255, 0, 0, 0.1);">
              <td colspan="4" style="text-align: left">
                <span style="font-weight: bold">Location: </span><span data-bind="text: LocationLabelDisplay()"></span>&nbsp;&nbsp;
                <span style="font-weight: bold">Contact Type: </span><span data-bind="text: ContactLabelDisplay()"></span>
              </td>
            </tr>
            <tr><td colspan="5"><hr></td></tr>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="2" style="text-align: right">
								Total Minutes
							</th>
							<td style="text-align: right" data-bind="text: Note.totalActivityMins()"></td>
              <td colspan="2"><span style="font-weight: bold;">&nbsp;&nbsp;Total Units</span>&nbsp;&nbsp;<span data-bind="text: Note.totalActivityUnits()"></span></td>
						</tr>
					</tfoot>
				</table>
			</div>

      <span class="section-title" style="text-align: center;">Progress Towards Goals &amp; Objectives</span>

      
			<div data-bind="foreach: Note.Problems">  
				<div class="form-section">
					<table>
						<thead>
							<tr>
								<th style="width: 16%;">Functional Area</th>
								<td data-bind="text: Area"></td>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th>Problem&nbsp;&nbsp;</th>
								<td data-bind="text: Problem"></td>
							</tr>
						</tbody>
					</table>

					<table>
						<tbody>
							<tr>
								<th style="width: 16%;">Activities&nbsp;&nbsp;</th>
								<td data-bind="text: Activities"></td>
							</tr>
						</tbody>
					</table>

          <!-- div style="font-weight: bold; text-align: center;">Notes</div -->
          <br>
          <span style="width: 100%; white-space: pre-wrap;" data-bind="text: ProgressNotes, disable: true" placeholder="Type notes here.  Delete section if not applicable."></span>
          
				</div>
			</div>
 			<div id="section-discharge" class="form-section" data-bind="visible: Note.TCMServicePlanId() == 0 || Note.TCMServicePlanFinalizedDate() ==  null" style="font-weight: bold">
      Thirty-day assessment period is in progress.  Goals and objectives will be identified after assessment is completed.
			</div>      
      <br>
		</div>
	</body>
</html>