<a href="<?php echo $this->rootDirectory ?>/forms/TCMNote/full-report.php?id=<?php echo $this->formData['Note']['Id']; ?>">VIEW 'Full Report' / PRINT</a><br>
<label class="bold">Date Written:</label> <span class="text"><?php echo ($this->formData['Note']['DateWritten'] === null ? 'Not Specified' : $this->formData['Note']['DateWritten']); ?></span><br>
<!--<label class="bold">Most Recent Service Plan Date:</label> <span class="text"><?php //echo ($this->formData['ServicePlan']['DateComplete'] === null ? '<span style="color: red;">In Progress</span>' : $this->formData['ServicePlan']['DateComplete']); ?></span><br>-->
<label class="bold">Case Manager:</label> <span class="text"><?php echo $this->formData['Note']['CaseManagerName']; ?></span><br>
<label class="bold">Supervisor:</label> <span class="text"><?php echo $this->formData['Note']['CaseManagerSupervisorName']; ?></span><br>
<?php if($this->formData['Note']['FinalizedDate'] !== null) { ?>
<label class="bold">Finalized:</label> <span class="text"><?php echo $this->formData['Note']['FinalizedDate']; ?></span>
<?php } else { ?>
<label class="bold">Finalized:</label> <span class="text" style="color: red;">In Progress</span><br>
<?php } ?>
