CREATE TABLE IF NOT EXISTS `log_form_enhanced_prior_auth` (
  `id`                              int(11) NOT NULL AUTO_INCREMENT,
  `date`                            datetime NOT NULL,
  `pid`                             int(11) DEFAULT NULL,
  `user`                            varchar(255) default NULL,
  `groupname`                       varchar(255) default NULL,
  `authorized`                      tinyint(4)   default NULL,
  `activity`                        tinyint(4) DEFAULT NULL,
  `prior_auth_number`               varchar(35) DEFAULT NULL,
  `not_req`                         varchar(3) DEFAULT NULL,
  `comments`                        varchar(255) DEFAULT NULL,
  `ddesc`                           varchar(255) NOT NULL,
  `bodypart`                        varchar(120) NOT NULL,
  `auth_for`                        int(5) DEFAULT NULL,
  `date_auth_for`                   date NOT NULL,
  `ins_plan_num`                    int(5) DEFAULT NULL,
  `ins_auth_date`                   date NOT NULL,
  `prescription_num`                int(5) DEFAULT NULL,
  `re_eval`                         varchar(120) NOT NULL,
  `case_number`                     varchar(120) NOT NULL,
  `auth_from`                       date NOT NULL,
  `auth_to`                         date NOT NULL,
  `units`                           varchar(11) DEFAULT NULL,
  `auth_length`                     int(11) DEFAULT NULL,
  `dollar`                          int(10) DEFAULT NULL,
  `auth_contact`                    varchar(20) NOT NULL,
  `auth_phone`                      varchar(20) NOT NULL,
  `code1`                           int(11) DEFAULT NULL,
  `code2`                           int(10) DEFAULT NULL,
  `code3`                           int(10) DEFAULT NULL,
  `code4`                           int(10) DEFAULT NULL,
  `code5`                           int(10) DEFAULT NULL,
  `code6`                           int(10) DEFAULT NULL,
  `code7`                           int(10) DEFAULT NULL,
  `addused`                         int(10) DEFAULT NULL,
  `used`                            int(10) DEFAULT NULL,
  `archived`                        int(1) NOT NULL DEFAULT '0',
  `override`                        int(1) NOT NULL DEFAULT '0',
  `temp_auth`                       tinyint(1),
  `primary_auth`                    tinyint(1),
  `secondary_auth`                  tinyint(1),
  `form_enhanced_prior_auth_id`     int(11)      default NULL,
  `encounter_id`                    int(11)      default NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
