#!/bin/bash -e
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
# Copyright 2011-2014
# authors: Amalu Obinna <amaluobinna@aol.com>
#          Brady Miller <brady@sparmy.com>
#
# Debian package post installation script steps:
#  1) Collect setting from package configuration file
#  2) Install or Upgrade
#    -Install
#      a) Collect the MySQL root password (if possible)
#      b) Ensure LibreEHR MySQL database and user do not exist. (if applicable)
#      c) Configure LibreEHR (if applicable)
#      d) Configure Apache
#      e) Configure PHP
#    -Upgrade
#      a) Modify new LibreEHR version configuration files
#      b) Upgrade MySQL database(s)
#      c) Upgrade Access Controls
#      d) Copy over old configuration files
#          (Copy to files with .OLD extension to allow manual comparisons by user)
#  3) Modify permissions for writable directories
#  4) Secure the php installation/upgrading scripts (if applicable)
#  5) Modify the package configuration file
#  6) Display instructions on starting libreehr
#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
   configure)

      #constants and paths
      LOGDIR=/var/log/libreehr
      LOG=$LOGDIR/install
      CONFIGDIR=/etc/libreehr
      CONFIG=$CONFIGDIR/libreehr.conf
      TMPDIR=/tmp/libreehr-tmp
      WEB=/var/www
      LIBREEHR=$WEB/libreehr
      SITEDIR=$LIBREEHR/sites
      #hardcoded mysql user and database for install (not pertinent for upgrading)
      # upgrading can use whatever is found in libreehr/library/sqlconf.php
      INSTALL_USER=libreehr
      INSTALL_DATABASE=libreehr
      #auto install scripts
      INST=$LIBREEHR/contrib/util/installScripts/InstallerAuto.php
      INSTTEMP=$LIBREEHR/contrib/util/installScripts/InstallerAutoTemp.php
      #php and apache files
      PHP=/etc/php5/apache2/php.ini
      #web user and group
      WEB_GROUP=www-data
      WEB_USER=www-data

      #Standardized echo function to send to only log file
      #  requires one parameter (string)
      log_only () {
         echo "`date`: $1" >> $LOG
      }

      #Standardized exit functions to be used
      #  requires one parameter (string with reason for exiting)
      unable_exit () {
         echo "`date`: $1" >> $LOG
         echo "`date`: EXITING.........." >> $LOG
         exit 1
      }

      #function to check mysql for selected databases
      # 1st param is password, 2nd param database, 3rd param is host (optional), 4th param is user (optional)
      check_mysql () {
         if [ -n "$3" ]; then
            HOST=$3
         else
            HOST=localhost
         fi
         if [ -n "$4" ]; then
            USE=$4
         else
            USE=root
         fi

         if [ "`mysql -u "$USE" -h "$HOST" --password="$1" -e 'show databases' 2>/dev/null | awk '{ print $1}' | grep "^$2$"`" == "$2" ]; then
            return 0
         else
            return 1
         fi
      }

      #function to collect variables from config files
      # 1st param is variable name, 2nd param is filename 
      collect_var () {
         echo `grep -i "^[[:space:]]*$1[[:space:]=]" $2 | cut -d \= -f 2 | cut -d \; -f 1 | sed "s/[ 	'\"]//gi"`
      }      

      #function to insert variables into config files
      # 1st param is variable name, 2nd param is variable, 3rd param is filename
      insert_var () {
         sed -i 's@^[ 	]*'"$1"'[ 	=].*$@'"$1"' = '"$2"'@' "$3"
      }

      #function to prompt for input
      # 1st param is name, 2nd param is priority, 3rd param is where result gets sent back in
      # return the input
      prompt_input () {
         db_set "$1" ""
         db_fset "$1" seen false
         db_input "$2" "$1" || true
         db_go || true
         db_get "$1"
         local input_value="$RET"
         db_set "$1" ""
         db_fset "$1" seen false
         local __result=$3
         eval $__result="'$input_value'"
      }

      #collect scripting information from config file
      PROCESS=$(collect_var process $CONFIG)
      PLAN=$(collect_var plan $CONFIG)

      #Don't allow re-configuration
      if [ "$PROCESS" == "complete" ] ; then
         unable_exit "LibreEHR has already been configured."
      elif [ "$PROCESS" == "pending" ] ; then
         #continue with configuration
         log_only "Configuring package..."
      else
         unable_exit "Error reading process variable in configuration file."
      fi

      if [ "$PLAN" == "upgrade" ] ; then       
         #continue with upgrade
         OLD_VERSION=$(collect_var previous_version $CONFIG)
         log_only "Continuing Upgrade from ($OLD_VERSION)"

         #go to libreehr directory
         cd $LIBREEHR

         # NEED TO CONFIGURE APACHE BEFORE CONFIGURATION SINCE ZEND SUPPORT NEEDS PROPER CONFIGURATION
         # Activate the LibreEHR conf file for apache
         log_only "Activate LibreEHR config file for Apache"
         a2ensite libreehr.conf
         # Ensure the apache rewrite module is turned on
         a2enmod rewrite
         # Restart the apache server
         log_only "Restarting Apache service..."
         invoke-rc.d apache2 restart >> $LOG 2>&1

         #To support the multisite module, go through each site
         for dir in $(find $SITEDIR/* -maxdepth 0 -type d ); do
            #collect sitename
            SITENAME=$(basename "$dir")
            log_only "Configuring Site ($SITENAME)"

            #collect more information from config file
            SQLLOCATION=$(collect_var ${SITENAME}_sqllocation $CONFIG)
            SQLUSER=$(collect_var ${SITENAME}_sqluser $CONFIG)
            SQLPASSWORD=$(collect_var ${SITENAME}_sqlpassword $CONFIG)
            SQLDATABASE=$(collect_var ${SITENAME}_sqldatabase $CONFIG)
            SQLUTFFLAG=$(collect_var ${SITENAME}_sqlutfflag $CONFIG)

            #configure database configuration file
            insert_var "\$host" "\'$SQLLOCATION\';"             $SITEDIR/$SITENAME/sqlconf.php
            insert_var "\$login" "\'$SQLUSER\';"                $SITEDIR/$SITENAME/sqlconf.php
            insert_var "\$pass" "\'$SQLPASSWORD\';"             $SITEDIR/$SITENAME/sqlconf.php
            insert_var "\$dbase" "\'$SQLDATABASE\';"            $SITEDIR/$SITENAME/sqlconf.php
            insert_var "\$disable_utf8_flag" "$SQLUTFFLAG;"     $SITEDIR/$SITENAME/sqlconf.php
            sed -i "s/^[   ]*\$config[     =].*0/\$config = 1/" $SITEDIR/$SITENAME/sqlconf.php

            #upgrade the sql database
            CONC_VERSION=$(echo $OLD_VERSION | cut -d \- -f 1)
            echo "<?php \$_GET['site'] = '$SITENAME'; ?>" > $LIBREEHR/TEMPsql_upgrade.php
            cat $LIBREEHR/sql_upgrade.php >> $LIBREEHR/TEMPsql_upgrade.php
            sed -i "/input type='submit'/d" $LIBREEHR/TEMPsql_upgrade.php
            sed -i "s/!empty(\$_POST\['form_submit'\])/empty(\$_POST\['form_submit'\])/" $LIBREEHR/TEMPsql_upgrade.php
            sed -i "s/^[   ]*\$form_old_version[   =].*$/\$form_old_version = \"$CONC_VERSION\";/" $LIBREEHR/TEMPsql_upgrade.php
            php -f $LIBREEHR/TEMPsql_upgrade.php >> $LOG 2>&1
            rm -f $LIBREEHR/TEMPsql_upgrade.php

            #copy the old config file into new with the OLD at end to allow manual configuration of old
            # optional settings.
            if [ -d "$TMPDIR/libreehr_web_$OLD_VERSION/sites/$SITENAME" ]; then
              cp -f "$TMPDIR/libreehr_web_$OLD_VERSION/sites/$SITENAME/config.php" "$SITEDIR/$SITENAME/config.php.OLD"
            else
              #need to move from old location, so sitename will always be default in this case
              cp -f $TMPDIR/libreehr_web_$OLD_VERSION/includes/config.php $SITEDIR/default/config.php.OLD
            fi

            #log
            log_only "Upgraded LibreEHR site ($SITENAME) with sql database ($SQLDATABASE) and sql user ($SQLUSER)."

         done

         # if site-specific directories are in the old locations, move them.
         if [ -d $LIBREEHR/documents ]; then
           if [ "$(ls $LIBREEHR/documents)" ]; then
             mv -f  $LIBREEHR/documents/* $SITEDIR/default/documents/
           fi
           rm -rf $LIBREEHR/documents
         fi
         if [ -d $LIBREEHR/era ]; then
           if [ "$(ls $LIBREEHR/era)" ]; then
             mv -f  $LIBREEHR/era/* $SITEDIR/default/era/
           fi
           rm -rf $LIBREEHR/era
         fi
         if [ -d $LIBREEHR/edi ]; then
           if [ "$(ls $LIBREEHR/edi)" ]; then
             mv -f  $LIBREEHR/edi/* $SITEDIR/default/edi/
           fi
           rm -rf $LIBREEHR/edi
         fi
         if [ -d $LIBREEHR/custom/letter_templates ]; then
           if [ "$(ls $LIBREEHR/custom/letter_templates)" ]; then
             mv -f  $LIBREEHR/custom/letter_templates/* $SITEDIR/default/letter_templates/
           fi
           rm -rf $LIBREEHR/custom/letter_templates
         fi

         #secure libreehr
         chown -Rf root:root $LIBREEHR
         chmod 600 $LIBREEHR/acl_setup.php
         chmod 600 $LIBREEHR/acl_upgrade.php
         chmod 600 $LIBREEHR/sl_convert.php
         chmod 600 $LIBREEHR/setup.php
         chmod 600 $LIBREEHR/sql_upgrade.php
         chmod 600 $LIBREEHR/ippf_upgrade.php
         chmod 600 $LIBREEHR/gacl/setup.php

         #set writable files and directories (that are not within sites directory)
         chown $WEB_GROUP.$WEB_USER $LIBREEHR/interface/modules/zend_modules/config/application.config.php
         chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/library/freeb
         chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/interface/main/calendar/modules/PostCalendar/pntemplates/cache 
         chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/interface/main/calendar/modules/PostCalendar/pntemplates/compiled 
         chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/gacl/admin/templates_c 

         #set writable directories (that are within sites directory)
         # (go through each site)
         for dir in $(find $SITEDIR/* -maxdepth 0 -type d ); do
            #collect sitename
            SITENAME=$(basename "$dir")
            #set the writable directories
            chown -R $WEB_GROUP.$WEB_USER $SITEDIR/$SITENAME/documents
            chown -R $WEB_GROUP.$WEB_USER $SITEDIR/$SITENAME/edi
            chown -R $WEB_GROUP.$WEB_USER $SITEDIR/$SITENAME/era
            chown -R $WEB_GROUP.$WEB_USER $SITEDIR/$SITENAME/letter_templates
         done

         #update config file, change process to complete and remove others
         sed -i "s/^[ 	]*process[ 	=].*$/process=complete/" $CONFIG
         sed -i "/^[ 	]*plan[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*previous_version[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*.*sqllocation[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*.*sqluser[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*.*sqlpassword[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*.*sqldatabase[ 	=].*$/d" $CONFIG
         sed -i "/^[ 	]*.*sqlutfflag[ 	=].*$/d" $CONFIG

         #done upgrading
         prompt_input libreehr/success_upgrade critical ret_result 
         log_only "LibreEHR upgrade is complete."
         log_only "Recommend setting optional configuration settings in:"
         log_only "$SITEDIR/<sitename>/config.php"
         log_only "(We have renamed your old configuration files to *.OLD)"
         log_only "(We recommend you delete the *.OLD files when done)"
         log_only "We have placed backup of your old LibreEHR in $TMPDIR"
         log_only "(We recommend you copy this somewhere protected since it"
         log_only "contains confidential patient information)"

         #stop db
         db_stop

         exit 0

      elif [ "$PLAN" == "install" ] ; then
         #continue with installation
         log_only "Installing LibreEHR"
      else
         unable_exit "Error reading plan variable in configuration file."
      fi      

      #This Section edits the php.ini file to accomodate the proper functioning of LibreEHR using php
      log_only "Configuring PHP for LibreEHR"

      #check to ensure the php configuration file exists
      if [ -f $PHP ]; then
         # First, collect php variables
         collect_php () {
            echo `grep -i "^[[:space:]]*$1[[:space:]=]" $PHP | cut -d \= -f 2 | cut -d \; -f 1 | sed 's/[ 	M]//gi'`
         }
         collect_php_commented_out () {
            echo `grep -i "^;[[:space:]]*$1[[:space:]=]" $PHP | cut -d \= -f 2 | cut -d \; -f 1 | sed 's/[       M]//gi'`
         }
         TAG_TEXT="short_open_tag"
         TAG=$(collect_php "$TAG_TEXT")
         EXEC_TEXT="max_execution_time"
         EXEC=$(collect_php "$EXEC_TEXT")
         INPUT_TEXT="max_input_time"
         INPUT=$(collect_php "$INPUT_TEXT")
         MEM_TEXT="memory_limit"
         MEM=$(collect_php "$MEM_TEXT")
         DISP_TEXT="display_errors"
         DISP=$(collect_php "$DISP_TEXT")
         LOGG_TEXT="log_errors"
         LOGG=$(collect_php "$LOGG_TEXT")
         GLOB_TEXT="register_globals"
         GLOB=$(collect_php "$GLOB_TEXT")
         POST_TEXT="post_max_size"
         POST=$(collect_php "$POST_TEXT")
         UPLOAD_TEXT="file_uploads"
         UPLOAD=$(collect_php "$UPLOAD_TEXT")
         FILESIZE_TEXT="upload_max_filesize"
         FILESIZE=$(collect_php "$FILESIZE_TEXT")
         MAXINPUTVARS_TEXT="max_input_vars"
         MAXINPUTVARS=$(collect_php "$MAXINPUTVARS_TEXT")
         MAXINPUTVARS_IF_COMMENTED=$(collect_php_commented_out "$MAXINPUTVARS_TEXT")

         # Second, backup the php.ini file before modifying
         cp $PHP $PHP.BAK

         # Third, edit the required entries
         #  Do this in a for loop.
         #   First iteration will discover the recommended changes
         #   Second iteration will make the changes (if user request this)
         FLAG_ON=0
         process_php () {
            if [ "$3" -eq "1" ]; then
               # make rec to php.ini
               if [ "$FLAG_ON" -eq "0" ]; then
                  log_only "We changed the following setting(s) in your php configuration file at $PHP :"
               fi      
               FLAG_ON=1
            else
               # modify php.ini
               sed -i "s/^[ 	]*$1[ 	=].*$/$1 = $2/" $PHP
               log_only "Successfully set $1 = $2"  
            fi
         }
         process_php_commented_out () {
            if [ "$3" -eq "1" ]; then
               # make rec to php.ini
               if [ "$FLAG_ON" -eq "0" ]; then
                  log_only "We changed the following setting(s) in your php configuration file at $PHP :"
               fi
               FLAG_ON=1
            else
               # modify php.ini
               sed -i "s/^;[     ]*$1[   =].*$/$1 = $2/" $PHP
               log_only "Successfully set $1 = $2"
            fi
         }
         for i in `seq 1 2`; do
            if [ ! -z "$TAG" ] && [ "$TAG" != "On" ]; then
               process_php "$TAG_TEXT" "On" $i
            fi
            if [ ! -z "$EXEC" ] && [ "$EXEC" -lt "60" ]; then
               process_php "$EXEC_TEXT" "60" $i
            fi
            if [ ! -z "$INPUT" ] && [ "$INPUT" -lt "90" ]; then
               process_php "$INPUT_TEXT" "90" $i
            fi
            if [ ! -z "$MEM" ] && [ "$MEM" -lt "128" ]; then
               process_php "$MEM_TEXT" "128M" $i
            fi
            if [ ! -z "$DISP" ] && [ "$DISP" != "Off" ]; then
               process_php "$DISP_TEXT" "Off" $i
            fi
            if [ ! -z "$LOGG" ] && [ "$LOGG" != "On" ]; then
               process_php "$LOGG_TEXT" "On" $i
            fi
            if [ ! -z "$GLOB" ] && [ "$GLOB" != "Off" ]; then
               process_php "$GLOB_TEXT" "Off" $i
            fi
            if [ ! -z "$POST" ] && [ "$POST" -lt "30" ]; then
               process_php "$POST_TEXT" "30M" $i
            fi
            if [ ! -z "$UPLOAD" ] && [ "$UPLOAD" != "On" ]; then
               process_php "$UPLOAD_TEXT" "On" $i
            fi
            if [ ! -z "$FILESIZE" ] && [ "$FILESIZE" -lt "30" ]; then
               process_php "$FILESIZE_TEXT" "30M" $i
            fi
            if [ ! -z "$MAXINPUTVARS" ] && [ "$MAXINPUTVARS" -lt "3000" ]; then
               process_php "$MAXINPUTVARS_TEXT" "3000" $i
            fi
            if [ ! -z "$MAXINPUTVARS_IF_COMMENTED" ] && [ "$MAXINPUTVARS_IF_COMMENTED" -lt "3000" ]; then
               process_php_commented_out "$MAXINPUTVARS_TEXT" "3000" $i
            fi
            if [ "$FLAG_ON" -eq "0" ]; then
              log_only "Your PHP configuration is perfect for LibreEHR."
              break
            else
              if [ "$i" -eq "1" ]; then
                prompt_input libreehr/php_configure high ret_result
              fi
            fi
            if [ "$i" -eq "1" ]; then
               log_only "(We have placed a backup of your php configuration at $PHP.BAK)"
            fi
         done
      else
         #can't find php config file, so just echo instructions
         log_only "We recommend ensuring you have below settings in your php configuration file:"
         log_only "short_open_tag = On"
         log_only "max_execution_time = 60"
         log_only "max_input_time = 90"
         log_only "memory_limit = 128M"
         log_only "display_errors = Off"
         log_only "log_errors = On"
         log_only "register_globals = Off"
         log_only "post_max_size = 30M"
         log_only "file_uploads = On"
         log_only "upload_max_filesize = 30M"
         log_only "max_input_vars = 3000"
         log_only "(note max_input_vars setting only exists since php 5.3.9)"
      fi

      log_only "Done configuring PHP"

      # NEED TO CONFIGURE APACHE BEFORE CONFIGURATION SINCE ZEND SUPPORT NEEDS PROPER CONFIGURATION
      # Activate the LibreEHR conf file for apache
      log_only "Activate LibreEHR config file for Apache"
      a2ensite libreehr.conf
      # Ensure the apache rewrite module is turned on
      a2enmod rewrite
      # Restart the apache server
      log_only "Restarting Apache service..."
      invoke-rc.d apache2 restart >> $LOG 2>&1

      #collect the mysql root password (if applicable)
      MPASS=""
      if check_mysql "$MPASS" "mysql"; then
         log_only "Passed the mysql check loop"
      else
         #the blank initial mysql password didn't work, so prompt for password
         # (will give 3 chances to provide correct password)
         COUNTDOWN=1
         while true; do
            prompt_input libreehr/mysql_p_install_${COUNTDOWN} critical ret_result
            MPASS="$ret_result"
            if check_mysql "$MPASS" "mysql"; then
               #the mysql root password works, so can exit loop
               log_only "Passed the mysql check loop"
               break
            else
               #the mysql root password did not work
               if [ "$COUNTDOWN" -ge "3" ]; then
                  prompt_input libreehr/no_configure_mysql_root high ret_result
                  log_only "Will install LibreEHR, however will not configure LibreEHR. (unable to provide root password)"
                  break
               fi
            fi
            let "COUNTDOWN += 1"
         done
      fi

      #decide whether to configure LibreEHR after it is installed
      configure_flag=true 
      if check_mysql "$MPASS" "mysql"; then
         #before auto configuration, ensure the libreehr user and database do not exist
         # Check for libreehr database in mysql, if exist then will not configure
         if check_mysql "$MPASS" "$INSTALL_DATABASE"; then
            prompt_input libreehr/no_configure_mysql_database high ret_result
            log_only "Will install LibreEHR, however will not automatically configure LibreEHR. (MySQL database already exists)"
            configure_flag=false;
         fi
         # Check for LibreEHR user in mysql.user, if exist then will not configure
         USER=$(mysql -s -u root -h localhost --password="$MPASS" -e "SELECT User from mysql.user where User='$INSTALL_USER'")
         if [ "$USER" == "$INSTALL_USER" ]; then
            prompt_input libreehr/no_configure_mysql_user high ret_result
            log_only "Will install LibreEHR, however will not automatically configure LibreEHR. (MySQL user already exists)"
            configure_flag=false;
         fi
      else
         #the mysql root password didn't work, so do not configure LibreEHR
         log_only "Will install LibreEHR, however will not automatically configure LibreEHR. (root password did not work)"
         configure_flag=false;
      fi

      #go to libreehr directory
      cd $LIBREEHR

      #secure libreehr
      chown -Rf root:root $LIBREEHR

      #INSTALL/CONFIGURE LIBREEHR
      # Install libreehr
      if $configure_flag; then
         log_only "Installing/Configuring LibreEHR..."
      else
         log_only "Installing LibreEHR ..."
      fi

      # Set file and directory permissions (note use default site directory for new install)
      chmod 666 $SITEDIR/default/sqlconf.php
      chown $WEB_GROUP.$WEB_USER $LIBREEHR/interface/modules/zend_modules/config/application.config.php
      chown -R $WEB_GROUP.$WEB_USER $SITEDIR/default/documents
      chown -R $WEB_GROUP.$WEB_USER $SITEDIR/default/edi
      chown -R $WEB_GROUP.$WEB_USER $SITEDIR/default/era
      chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/library/freeb
      chown -R $WEB_GROUP.$WEB_USER $SITEDIR/default/letter_templates
      chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/interface/main/calendar/modules/PostCalendar/pntemplates/cache
      chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/interface/main/calendar/modules/PostCalendar/pntemplates/compiled
      chown -R $WEB_GROUP.$WEB_USER $LIBREEHR/gacl/admin/templates_c

      if $configure_flag; then
         # Create a random password for the libreehr mysql user
         password=$(makepasswd --char=12)

         # libreehr installation VARIABLES
         if [ "$MPASS" == "" ] ; then
           rootpass="rootpass=BLANK" #MySQL server root password
         else
           rootpass="rootpass=$MPASS" #MySQL server root password
         fi
         login="login=$INSTALL_USER" #username to MySQL libreehr database
         pass="pass=$password" #password to MySQL libreehr database
         dbname="dbname=$INSTALL_DATABASE" #MySQL libreehr database name
 
         # 
         # Run Auto Installer 
         #
         sed -e 's@^exit;@ @' <$INST >$INSTTEMP
         php -f $INSTTEMP $rootpass $login $pass $dbname >> $LOG 2>&1
         rm -f $INSTTEMP

         #remove global permission to all setup scripts
         chmod 600 $LIBREEHR/acl_setup.php
         chmod 600 $LIBREEHR/acl_upgrade.php
         chmod 600 $LIBREEHR/sl_convert.php
         chmod 600 $LIBREEHR/setup.php
         chmod 600 $LIBREEHR/sql_upgrade.php
         chmod 600 $LIBREEHR/ippf_upgrade.php
         chmod 600 $LIBREEHR/gacl/setup.php

         log_only "Done configuring LibreEHR"
      fi

      if $configure_flag; then
         prompt_input libreehr/success_install_config high ret_result
         log_only "You can now use LibreEHR by browsing to:"
         log_only "http://localhost/libreehr"
         log_only "user is 'admin' and password is 'pass'"
         log_only "See the libreehr man page for further instructions:"
         log_only "type 'man libreehr' at command line"
      else
         prompt_input libreehr/success_install high ret_result
         log_only "You can now configure LibreEHR by browsing to:"
         log_only "http://localhost/libreehr"
         log_only "See the libreehr man page for further instructions:"
         log_only "type 'man libreehr' at command line"
      fi

      #update config file, change process to complete and remove plan and pass
      sed -i "s/^[ 	]*process[ 	=].*$/process=complete/" $CONFIG
      sed -i "/^[ 	]*plan[ 	=].*$/d" $CONFIG

      #stop db
      db_stop

      exit 0
   ;;
   abort-upgrade|abort-remove|abort-deconfigure)
   
      echo "postinst asked to do $1"
      exit 0
   ;;
   *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 1
   ;;
esac

sleep 5
exit 0
