<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Assessment</title>
		<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot']; ?>/interface/themes/style_oemr.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory ?>/forms/TCMAssessment/style.css">
		<script type="text/javascript" src="<?php echo $GLOBALS['webroot']; ?>/library/js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/Types.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/AssessmentSubModels.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/Assessment.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/AssessmentViewModel.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				AssessmentVM = new AssessmentViewModel;
				AssessmentVM.Load({
					AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/ajax.php',
					WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
					ExitUri: '<?php echo $GLOBALS['form_exit_url']; ?>',
					AssessmentId: '<?php echo $this->assessmentId; ?>',
					TestMode: false
				});
				ko.applyBindings(AssessmentVM);
			});
		</script>
		
		<!-- wkr20170607:  maybe move honorlinebreak style to common stylesheet? -->
		<style>  
			.honorlinebreak { white-space: pre-wrap }
		</style>
	</head>
	<body class="bgcolor2">
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div id="hoverMenu">
			<div>
				<div class="css_button" data-bind="click: Exit"><span>Cancel</span></div>
				<div class="css_button" data-bind="click: Print"><span>Print</span></div>
			</div>
		</div>
		<div class="contentWraper">
			<h1>Targeted Case Management Assessment</h1>
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>
			<div id="section-client-info" class="form-section">
				<table>
					<tbody>
						<tr>
							<th>Assessment</th>
							<td colspan="3" data-bind="text: Assessment.TypeDisplay"></td>
						</tr>
						<tr>
							<th>Clients Name</th>
							<td data-bind="text: Assessment.ClientName"></td>
							<th>Date of Birth</th>
							<td data-bind="text: Assessment.ClientBirth"></td>
						</tr>
						<tr>
							<th>Medicaid #</th>
							<td data-bind="text: Assessment.MedicaidId"></td>
							<th>Admit Date</th>
							<td style="width: 10ex;" data-bind="text: Assessment.AdmitDate"></td>
						</tr>
						<tr>
							<th>Home Visit Date(s)</th>
							<td data-bind="text: Assessment.HomeVisitDates"></td>
							<th>Report Date</th>
							<td data-bind="text: Assessment.Encounter.ReportDate"></td>
						</tr>
						<tr>
							<th>Targeted Case Manager</th>
							<td data-bind="text: Assessment.CaseManagerName"></td>
							<th>Supervisor</th>
							<td data-bind="text: Assessment.CaseManagerSupervisorName"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-sources" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="2">
								<span class="section-title">Sources of Information</span>
								<span class="section-subtitle">(Information from interviews and records used to complete the assessment)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.SourcesActive().length > 0">
							<th style="width: 100%">Individual or Document Type</th>
							<th>Date</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Sources">
						<tr>
							<td data-bind="text: Type"></td>
							<td style="width: 10ex;" data-bind="text: Date"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-presenting-reason" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Presenting Problems / Reason for Referral</span>
								<span class="section-subtitle">(Include referral source and client, legal guardian and family's perspective of the problem)</span>
							</th>
						</tr>
					</thead>
				</table>
				
				<!-- wkr20170607 -->
				<table>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.Encounter.ProblemReason" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>

			</div>
			
			<!-- wkr20170607 -->
			<div id="section-current-circumstances" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Current Circumstances</span>
							</th>
						</tr>
					</thead>
				</table>				
				<table>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.CurrentCircumstances" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>

			</div>
			
			
			<div id="section-personal-family-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Personal and Family History</span>
								<span class="section-subtitle">(Include child/family factors that may have contributed to need for services; child welfare involvement including reason for removal of child; history of abuse/neglect/domestic violence exposure; deaths, separation/divorce; multiple caregivers; family history of criminal charges, mental health diagnoses or substance abuse and any family history of treatment)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.FamilyHistory" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.FamilyHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-treatment-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Treatment History</span>
								<span class="section-subtitle">(Include any previous psychiatric hospitalizations/mental health treatment or other services)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.TreatmentHistoryActive().length > 0">
							<th>Agency/Provider</th>
							<th>Dates of Treatment</th>
							<th>Type of Treatment</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.TreatmentHistory">
						<tr>
							<td data-bind="text: Provider"></td>
							<td data-bind="text: Dates"></td>
							<td data-bind="text: Type"></td>
						</tr>
					</tbody>
				</table>
					
				<!-- wkr20170531 -->
				<table>		
					<tbody>
						<tr>
							<td data-bind="text: Assessment.TreatmentHistoryNotes" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>
					
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.TreatmentHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-medical-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="5">
								<span class="section-title">Medical History</span>
								<span class="section-subtitle">(Include current medical history/conditions, dental and vision)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicalHistoryActive().length > 0">
							<th>Type of Health Care</th>
							<th>Provider</th>
							<th>Last Exam</th>
							<th>Findings</th>
							<th>Known Medical Conditions/Allergies</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicalHistory">
						<tr>
							<td data-bind="text: Type"></td>
							<td data-bind="text: Provider"></td>
							<td data-bind="text: LastExam"></td>
							<td data-bind="text: Findings"></td>
							<td data-bind="text: KnownConditions"></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="5">Notes</th>
						</tr>
						<tr>
							<td colspan="5" data-bind="text: Assessment.MedicalHistoryNotes" class="honorlinebreak"></td>
						</tr>
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-current-medications" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="4">
								<span class="section-title">Current Medications</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicationsActiveCurrent().length > 0">
							<th>Entered On</th>
							<th>Medication / Frequency</th>
							<th>Date Started</th>
							<th>Date Ended</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicationsCurrent">
						<tr>
							<td data-bind="text: Date"></td>
							<td data-bind="text: Title"></td>
							<td style="width: 10ex;" data-bind="text: BeginDate"></td>
							<td style="width: 10ex;" data-bind="text: EndDate"></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="4">Notes</th>
						</tr>
						<tr>
							<td colspan="4" data-bind="text: Assessment.MedicationsCurrentNotes" class="honorlinebreak"></td>
						</tr>
					</tfoot>
				</table>
						
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicationsCurrentSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-past-medications" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="4">
								<span class="section-title">Past Medications</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicationsActivePast().length > 0">
							<th>Entered On</th>
							<th>Medication / Frequency</th>
							<th>Date Started</th>
							<th>Date Ended</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicationsPast">
						<tr>
							<td data-bind="text: Date"></td>
							<td data-bind="text: Title"></td>
							<td style="width: 10ex;" data-bind="text: BeginDate"></td>
							<td style="width: 10ex;" data-bind="text: EndDate"></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="4">Notes</th>
						</tr>
						<tr>
							<td colspan="4" data-bind="text: Assessment.MedicationsPastNotes" class="honorlinebreak"></td>
						</tr>
					</tfoot>
					
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicationsPastSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-educational-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="6">
								<span class="section-title">Educational History</span>
								<span class="section-subtitle">(Include information about any previous or current psychological testing or behavior plans)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.EducationalHistoryActive().length > 0">
							<th>School Name</th>
							<th>Grade(s)</th>
							<th>Classroom Type (mainstream, EH, SED, EMH, etc)</th>
							<th>Individualized Education Plan (IEP) / 504 Plan (SLD, Testing, services)</th>
							<th>Academic Performance (Above average, average, needs improvement, poor)</th>
							<th>Classroom Behavior (Cooperative/on-task, distracted, defiant, disruptive)</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.EducationalHistory()">
						<tr>
							<td data-bind="text: School"></td>
							<td data-bind="text: Grades"></td>
							<td data-bind="text: Type"></td>
							<td data-bind="text: Plan"></td>
							<td data-bind="text: Performance"></td>
							<td data-bind="text: Behavior"></td>
						</tr>
					</tbody>
					
					<tfoot>
						<tr>
							<th colspan="6">Notes</th>
						</tr>
						<tr>
							<td colspan="6" data-bind="text: Assessment.EducationalHistoryNotes" class="honorlinebreak"></td>
						</tr>
					</tfoot>
					
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.EducationalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-substance-abuse" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="2">
								<span class="section-title">Substance Abuse</span>
								<span class="section-subtitle">(For ages 10 and older)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.SubstanceAbuseActive().length === 0">
							<td colspan="2">No known substance use involvement</td>
						</tr>
						<tr data-bind="visible: Assessment.SubstanceAbuseActive().length > 0">
							<th>Substances (nicotine, prescriptions/OTC, alcohol, drugs)</th>
							<th>Frequency of use (one time, previous use, current/ongoing)</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.SubstanceAbuse()">
						<tr>
							<td data-bind="text: Substance"></td>
							<td data-bind="text: Frequency"></td>
						</tr>
					</tbody>

					<tfoot>
						<tr>
							<th colspan="2">Notes</th>
						</tr>
						<tr>
							<td colspan="2" data-bind="text: Assessment.SubstanceAbuseNotes" class="honorlinebreak"></td>
						</tr>						
					</tfoot>					
					
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.SubstanceAbuseSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-vocational-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Vocational History</span>
								<span class="section-subtitle">(For ages 14 and older; vocational aptitude and interest evaluation, previous employment and acquired vocational skills, activities and interests)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.VocationalHistory" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.VocationalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-legal-dependency-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Legal & Dependency History</span>
								<span class="section-subtitle">(Include any criminal history, custody issues and child welfare involvement/case plan permanency goal)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.LegalDependencyHistory" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="2">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.LegalDependencyHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td data-bind="text: Date"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div id="section-significant-relationships" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Significant Relationships</span>
								<span class="section-subtitle">(Include skills that help maintain relationship with family, friends and any other significant relationships from client/family perspective)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.SignificantRelationships"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-potential-strengths" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="2">
								<span class="section-title">Current and Potential Strengths</span>
								<span class="section-subtitle">(Include strengths from client/family perspective)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Client reports strengths are</td>
							<td data-bind="text: Assessment.PotentialStrengths.Client"></td>
						</tr>
						<tr>
							<td>Parents report client strengths are</td>
							<td data-bind="text: Assessment.PotentialStrengths.Parent"></td>
						</tr>
						<tr>
							<td>Family strengths are</td>
							<td data-bind="text: Assessment.PotentialStrengths.Family"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-resources-available" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Resources Available</span>
								<span class="section-subtitle">(include what is available to client through natural support systems, basic needs, financial resources, health care,  etc)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="text: Assessment.ResourcesAvailable" class="honorlinebreak"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-safety-assessment" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Safety Assessment</span>
								<span class="section-subtitle">(Indicate any risk factors for this client , including personal/interpersonal factors and physical home environment. If there are identified risk factors, the current safety or risk management plan must be included)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="foreach: Assessment.Safety.Types" style="column-count: 2; -moz-column-count: 2; -webkit-column-count: 2;">
								<div>
									<input type="checkbox" data-bind="checked: Selected" disabled="disabled">
									<label data-bind="text: Type().Label"></label>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
				<br>
				<table>
					<tbody>
						<tr>
							<td>Other</td>
							<td data-bind="text: Assessment.Safety.Other"></td>
						</tr>
						<tr>
							<td>Brief description of risk factors above</td>
							<td data-bind="text: Assessment.Safety.Description"></td>
						</tr>
						<tr>
							<td>Safety/Risk Plan</td>
							<td data-bind="text: Assessment.Safety.Plan"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-current-services" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="4">
								<span class="section-title">Current Services</span>
								<span class="section-subtitle">(Include all current services being provided and effectiveness)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.CurrentServicesActive().length > 0">
							<th>Agency/Provider</th>
							<th>Date Service Began</th>
							<th>Service</th>
							<th>Effectiveness</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.CurrentServices">
						<tr>
							<td data-bind="text: Provider"></td>
							<td data-bind="text: DateBegin"></td>
							<td><div data-bind="visible: Type() !== '0'"><select data-bind="options: $root.CurrentServicesTypes, value: Type, optionsValue: 'Id', optionsText: 'Label', optionsCaption: 'Choose...'"></select></div><div data-bind="visible: Type() === '0'"><input type="text" data-bind="value: TypeOther"></div></td>
							<td data-bind="text: Effectiveness"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-functional-assessment" class="form-section">
				<table class="center">
					<thead>
						<tr>
							<th>Functional Assessment</th>
							<th>Fully functioning; no current service needs</th>
							<th>Partial functioning; some service needs</th>
							<th>Low functioning; immediate service needs</th>
							<th>Client/Family has ability & willingness to address this goal</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Functional">
						<tr>
							<th>
								<span class="section-title" data-bind="text: Type().Label"></span>
								<span class="section-subtitle" data-bind="text: Type().Description"></span>
							</th>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="no" disabled="disabled"></td>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="some" disabled="disabled"></td>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="immediate" disabled="disabled"></td>
							<td><input type="checkbox" data-bind="checked: Willingness" value="true" disabled="disabled"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-service-needs-recommendations" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Needs and Recommendations</span>
							</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Functional">
						<!-- ko if: Willingness -->
						<tr>
							<td>
								<span class="subsection-title" data-bind="text: Type().Label"></span>
							</td>
						</tr>
						<tr>
							<td>Needs</td>
						</tr>
						<tr>
							<td data-bind='text: NeedSummary'></td>
						</tr>
						<tr>
							<td>Recommended TCM Activities</td>
						</tr>
						<tr>
							<td data-bind='text: ActivityRecommendations'></td>
						</tr>
						<!-- /ko -->
					</tbody>
				</table>
			</div>
			<div id="section-signatures" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Signatures</span>
							</th>
						</tr>
						<tr>
							<th style="width: 14em;"></th>
							<th>Name</th>
							<th style="width: 10em;">Signature Date</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>Case Manager</th>
							<td data-bind="text: Assessment.CaseManagerName"></td>
							<td data-bind="text: Assessment.Signatures.CaseManager"></td>
						</tr>
						<tr data-bind="visible: Assessment.CaseManagerSupervisorName">
							<th>Case Manager Supervisor</th>
							<td data-bind="text: Assessment.CaseManagerSupervisorName"></td>
							<td data-bind="text: Assessment.Signatures.Supervisor"></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</body>
</html>