<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Assessment</title>
		<script type="text/javascript" src="<?php echo $GLOBALS['webroot']; ?>/library/js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/AssessmentNewViewModel.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js"></script>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/style.css">
		<script type="text/javascript">
			$(document).ready(function() {
				AssessmentVM = new AssessmentNewViewModel;
				AssessmentVM.Load({
					AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/ajax.php',
					WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
					TestMode: false
				});
				ko.applyBindings(AssessmentVM);
			});
		</script>
	</head>
	<body>
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div class="contentWraper">
			<h1>Targeted Case Management Assessment</h1>
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>
			<div id="section-client-info" class="form-section">
				<table>
					<tbody>
						<tr>
							<th>Clients Name</th>
							<td data-bind="text: Assessment.ClientName"></td>
							<th>Date of Birth</th>
							<td data-bind="text: Assessment.ClientBirth"></td>
						</tr>
						<tr>
							<th>Medicaid #</th>
							<td colspan="3" data-bind="text: Assessment.MedicaidId"></td>
						</tr>
						<tr>
							<th>Targeted Case Manager</th>
							<td data-bind="text: Assessment.CaseManagerName"></td>
							<th>Supervisor</th>
							<td data-bind="text: Assessment.CaseManagerSupervisorName"></td>
						</tr>
						<tr>
							<td colspan="4">
								<input type="radio" id="assessment-type-initial" data-bind="checked: Assessment.Type" value="INITIAL">
								<label for="assessment-type-initial">Initial</label>
								<input type="radio" id="assessment-type-update" data-bind="checked: Assessment.Type" value="UPDATE">
								<label for="assessment-type-update">Annual Update</label>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<a class="css_button" data-bind="click: Save"><span>Create Assessment</span></a>
			<a href="<?php echo $GLOBALS['form_exit_url']; ?>" class="css_button" data-bind="click: Cancel"><span>Cancel</span></a>
		</div>
	</body>	
</html>
