<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Assessment</title>
		<script type="text/javascript" src="<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-1.9.1.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/Types.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/AssessmentSubModels.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/Assessment.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/AssessmentViewModel.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js"></script>
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/modernizr-custom-2.6.2.js"></script>
		<script>
			Modernizr.load({
				test: Modernizr.inputtypes.date,
				nope: [
					'<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-ui-1.8.21.custom.min.js',
					'<?php echo $GLOBALS['webroot']; ?>/library/css/jquery-ui-1.8.21.custom.css'
				],
				complete: function () {
					$(document).ready(function() {
						if (typeof jQuery.ui !== 'undefined') {
							$('input[type=date]').datepicker({
								dateFormat: 'yyyy-mm-dd'
							}); 
						}

						AssessmentVM = new AssessmentViewModel;
						AssessmentVM.Load({
							AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/ajax.php',
							WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
							ExitUri: '<?php echo $GLOBALS['form_exit_url']; ?>',
							AssessmentId: '<?php echo $this->assessmentId; ?>',
							TestMode: false
						});
						ko.applyBindings(AssessmentVM);
					});
				}
			});
		</script>
		<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot']; ?>/interface/themes/style_oemr.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory ?>/forms/TCMAssessment/style.css">
	</head>
	<body class="bgcolor2">
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div id="hoverMenu">
			<div>
				<div class="css_button" data-bind="click: Save"><span>Save Assessment</span></div>
				<div class="css_button" data-bind="click: Exit"><span>Cancel</span></div>
				<div class="css_button" data-bind="click: Assessment.ManagerNoteVisibleToggle"><span>Manager Notes</span></div>
				<div class="css_button" style="float: right;" data-bind="visible: Assessment.Signatures.Display, click: Assessment.Signatures.VisibleToggle"><span>Signatures</span></div>
			</div>
			<div id="managerNotes" data-bind="visible: Assessment.ManagerNoteVisible">
				<div>
					<textarea data-bind="value: Assessment.ManagerNote"></textarea>
				</div>
			</div>
			<div id="signatures" data-bind="visible: Assessment.Signatures.Visible">
				<div>
					<div>
						<table>
							<thead>
								<tr>
									<th>Case Manager Signature</th>
									<th>Supervisor Signature</th>
								</tr>
							</thead>
							<tbody>
									<tr>
										<td>
											<div style="width: 16em;">
												<div data-bind="visible: Assessment.Signatures.DisplayCaseManager">
													<div class="css_button" data-bind="click: SignatureCaseManager"><span>Case Manager Signature</span></div>
												</div>
												<span data-bind="visible: !Assessment.Signatures.DisplayCaseManager()">
													<span data-bind="text: Assessment.Signatures.CaseManager"></span>
												</span>
											</div>
										</td>
										<td>
											
											<div style="width: 16em;">
												<div data-bind="visible: Assessment.Signatures.DisplaySupervisor">
													<div class="css_button" data-bind="click: SignatureSupervisor"><span>Supervisor Signature</span></div>
												</div>
												<span data-bind="visible: !Assessment.Signatures.DisplaySupervisor()">
													<span data-bind="text: Assessment.Signatures.Supervisor"></span>
												</span>
											</div>
										</td>
									</tr>
									<tr data-bind="visible: Assessment.Signatures.DisplayRevert">
										<td colspan="2">
											<div style="width: 16em;">
												<div class="css_button" data-bind="click: SignatureRevert"><span>Revert Signature(s)</span></div>
											</div>
										</td>
									</tr>
							</tbody>
						</table>
					</div>
					<div style="clear: both;"></div>
				</div>
			</div>
		</div>
		<div class="contentWraper">
			<h1>Targeted Case Management Assessment</h1>
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>
			<div id="section-client-info" class="form-section">
				<table>
					<tbody>
						<tr>
							<th>Assessment</th>
							<td colspan="3"><span data-bind="text: Assessment.TypeDisplay"></span></td>
						</tr>
						<tr>
							<th>Clients Name</th>
							<td><span data-bind="text: Assessment.ClientName"></span></td>
							<th>Date of Birth</th>
							<td><span data-bind="text: Assessment.ClientBirth"></span></td>
						</tr>
						<tr>
							<th>Medicaid #</th>
							<td><span data-bind="text: Assessment.MedicaidId"></span></td>
							<th>Admit Date</th>
							<td style="width: 10ex;"><input type="date" data-bind="value: Assessment.AdmitDate"></td>
						</tr>
						<tr>
							<th>Home Visit Date(s)</th>
							<td><input type="text" data-bind="value: Assessment.HomeVisitDates"></td>
							<th>Report Date</th>
							<td><span title="Date will be updated to today on save." data-bind="text: Assessment.Encounter.ReportDate"></span></td>
						</tr>
						<tr>
							<th style="width: 25%">Targeted Case Manager</th>
							<td style="width: 25%"><span data-bind="text: Assessment.CaseManagerName"></span></td>
							<th style="width: 25%">Supervisor</th>
							<td style="width: 25%"><span data-bind="text: Assessment.CaseManagerSupervisorName"></span></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-sources" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Sources of Information</span>
								<span class="section-subtitle">(Information from interviews and records used to complete the assessment)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.SourcesActive().length > 0">
							<th>Individual or Document Type</th>
							<th style="width: 10ex;">Date</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Sources">
						<tr>
							<td><input type="text" data-bind="value: Type" /></td>
							<td><input type="date" data-bind="value: Date" /></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.SourcesRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="3" class="onlyButton"><button class="ico-plus" title="Add Source" data-bind="click: Assessment.SourcesAddNew"></button></td>
						</tr>
					</tfoot>
				</table>
			</div>
			<div id="section-presenting-reason" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Presenting Problems / Reason for Referral</span>
								<span class="section-subtitle">(Include referral source and client, legal guardian and family's perspective of the problem)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.Encounter.ProblemReason"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			
			<!-- wkr20170531 -->
			<div id="section-current-circumstances" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Current Circumstances</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.CurrentCircumstances"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			
			
			
			<div id="section-personal-family-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Personal and Family History</span>
								<span class="section-subtitle">(Include child/family factors that may have contributed to need for services; child welfare involvement including reason for removal of child; history of abuse/neglect/domestic violence exposure; deaths, separation/divorce; multiple caregivers; family history of criminal charges, mental health diagnoses or substance abuse and any family history of treatment)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.FamilyHistory"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.FamilyHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.FamilyHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.FamilyHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.FamilyHistorySources.DisplaySet, enable: Assessment.FamilyHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.FamilyHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.FamilyHistorySources.SourcesAvailable(), value: Assessment.FamilyHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.FamilyHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-treatment-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="4">
								<span class="section-title">Treatment History</span>
								<span class="section-subtitle">(Include any previous psychiatric hospitalizations/mental health treatment or other services)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.TreatmentHistoryActive().length > 0">
							<th>Agency/Provider</th>
							<th>Dates of Treatment</th>
							<th>Type of Treatment</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.TreatmentHistory">
						<tr>
							<td><input type="text" data-bind="value: Provider" /></td>
							<td><input type="text" data-bind="value: Dates" /></td>
							<td><input type="text" data-bind="value: Type" /></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.TreatmentHistoryRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="4" class="onlyButton"><button class="ico-plus" title="Add History" data-bind="click: Assessment.TreatmentHistoryAddNew"></button></td>
						</tr>
						<!-- wkr20170531 -->
						<tr>
							<th colspan="4">Notes</th>
						</tr>
						<tr>
							<td colspan="4">
								<textarea data-bind="value: Assessment.TreatmentHistoryNotes"></textarea>
							</td>
						</tr>
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.TreatmentHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.TreatmentHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
						
						
						
							<tr data-bind="visible: !Assessment.TreatmentHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.TreatmentHistorySources.DisplaySet, enable: Assessment.TreatmentHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.TreatmentHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.TreatmentHistorySources.SourcesAvailable(), value: Assessment.TreatmentHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.TreatmentHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-medical-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="6">
								<span class="section-title">Medical History</span>
								<span class="section-subtitle">(Include current medical history/conditions, dental and vision)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicalHistoryActive().length > 0">
							<th>Type of Health Care</th>
							<th>Provider</th>
							<th>Last Exam</th>
							<th>Findings</th>
							<th>Known Medical Conditions/Allergies</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicalHistory">
						<tr>
							<td><input type="text" data-bind="value: Type"></td>
							<td><input type="text" data-bind="value: Provider"></td>
							<td><input type="text" data-bind="value: LastExam"></td>
							<td><input type="text" data-bind="value: Findings"></td>
							<td><input type="text" data-bind="value: KnownConditions"></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicalHistoryRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="6" class="onlyButton"><button class="ico-plus" title="Add History" data-bind="click: Assessment.MedicalHistoryAddNew"></button></td>
						</tr>
						<tr>
							<th colspan="6">Notes</th>
						</tr>
						<tr>
							<td colspan="6">
								<textarea data-bind="value: Assessment.MedicalHistoryNotes"></textarea>
							</td>
						</tr>
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicalHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.MedicalHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.MedicalHistorySources.DisplaySet, enable: Assessment.MedicalHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.MedicalHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.MedicalHistorySources.SourcesAvailable(), value: Assessment.MedicalHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.MedicalHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-current-medications" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="5">
								<span class="section-title">Current Medications</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicationsActiveCurrent().length > 0">
							<th>Entered On</th>
							<th>Medication / Frequency</th>
							<th style="width: 10ex;">Date Started</th>
							<th style="width: 10ex;">Date Ended</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicationsCurrent">
						<tr>
							<td data-bind="text: Date"></td>
							<td><input type="text" data-bind="value: Title"></td>
							<td><input type="date" data-bind="value: BeginDate"></td>
							<td><input type="date" data-bind="value: EndDate"></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicationsRemove"></button></td>
						</tr>
							
					</tbody>
					<tfoot>
						<tr>
							<td colspan="5" class="onlyButton"><button class="ico-plus" title="Add Medication" data-bind="click: Assessment.MedicationsAddNewCurrent"></button></td>
						</tr>
						<!-- wkr20170531 -->
						<tr>
							<th colspan="5">Notes</th>
						</tr>
						<tr>
							<td colspan="5">
								<textarea data-bind="value: Assessment.MedicationsCurrentNotes"></textarea>
							</td>
						</tr>
						
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicationsCurrentSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicationsCurrentSources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.MedicationsCurrentSources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.MedicationsCurrentSources.DisplaySet, enable: Assessment.MedicationsCurrentSources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.MedicationsCurrentSources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.MedicationsCurrentSources.SourcesAvailable(), value: Assessment.MedicationsCurrentSources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.MedicationsCurrentSources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-past-medications" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="5">
								<span class="section-title">Past Medications</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.MedicationsActivePast().length > 0">
							<th>Entered On</th>
							<th>Medication / Frequency</th>
							<th style="width: 10ex;">Date Started</th>
							<th style="width: 10ex;">Date Ended</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.MedicationsPast">
						<tr>
							<td data-bind="text: Date"></td>
							<td><input type="text" data-bind="value: Title"></td>
							<td><input type="date" data-bind="value: BeginDate"></td>
							<td><input type="date" data-bind="value: EndDate"></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicationsRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="5" class="onlyButton"><button class="ico-plus" title="Add Medication" data-bind="click: Assessment.MedicationsAddNewPast"></button></td>
						</tr>
						
						<!-- wkr20170531 -->
						<tr>
							<th colspan="5">Notes</th>
						</tr>
						<tr>
							<td colspan="5">
								<textarea data-bind="value: Assessment.MedicationsPastNotes"></textarea>
							</td>
						</tr>

						
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.MedicationsPastSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.MedicationsPastSources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.MedicationsPastSources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.MedicationsPastSources.DisplaySet, enable: Assessment.MedicationsPastSources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.MedicationsPastSources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.MedicationsPastSources.SourcesAvailable(), value: Assessment.MedicationsPastSources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.MedicationsPastSources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-educational-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="7">
								<span class="section-title">Educational History</span>
								<span class="section-subtitle">(Include information about any previous or current psychological testing or behavior plans)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.EducationalHistoryActive().length > 0">
							<th>School Name</th>
							<th>Grade(s)</th>
							<th>Classroom Type (mainstream, EH, SED, EMH, etc)</th>
							<th>Individualized Education Plan (IEP) / 504 Plan (SLD, Testing, services)</th>
							<th>Academic Performance (Above average, average, needs improvement, poor)</th>
							<th>Classroom Behavior (Cooperative/on-task, distracted, defiant, disruptive)</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.EducationalHistory()">
						<tr>
							<td><input type="text" data-bind="value: School" /></td>
							<td><input type="text" data-bind="value: Grades" /></td>
							<td><input type="text" data-bind="value: Type" /></td>
							<td><input type="text" data-bind="value: Plan" /></td>
							<td><input type="text" data-bind="value: Performance" /></td>
							<td><input type="text" data-bind="value: Behavior" /></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.EducationalHistoryRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="7" class="onlyButton"><button class="ico-plus" title="Add History" data-bind="click: Assessment.EducationalHistoryAddNew"></button></td>
						</tr>
						
						<!-- wkr20170531 -->
						<tr>
							<th colspan="7">Notes</th>
						</tr>
						<tr>
							<td colspan="7">
								<textarea data-bind="value: Assessment.EducationalHistoryNotes"></textarea>
							</td>
						</tr>
						
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.EducationalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.EducationalHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.EducationalHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.EducationalHistorySources.DisplaySet, enable: Assessment.EducationalHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.EducationalHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.EducationalHistorySources.SourcesAvailable(), value: Assessment.EducationalHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.EducationalHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-substance-abuse" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Substance Abuse</span>
								<span class="section-subtitle" data-bind="style: { color: Assessment.SubstanceAbuseAge() ? 'red' : '' }">(For ages 10 and older)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.SubstanceAbuseAge()">
							<td colspan="3">Client is not old enough for this section</td>
						</tr>
						<tr data-bind="visible: Assessment.SubstanceAbuseActive().length === 0 && !Assessment.SubstanceAbuseAge()">
							<td colspan="3">No known substance use involvement</td>
						</tr>
						<tr data-bind="visible: Assessment.SubstanceAbuseActive().length > 0">
							<th>Substances (nicotine, prescriptions/OTC, alcohol, drugs)</th>
							<th>Frequency of use (one time, previous use, current/ongoing)</th>
							<th></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.SubstanceAbuse()">
						<tr>
							<td><input type="text" data-bind="value: Substance" /></td>
							<td><input type="text" data-bind="value: Frequency" /></td>
							<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.SubstanceAbuseRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="3" class="onlyButton"><button class="ico-plus" title="Add Substance"  data-bind="click: Assessment.SubstanceAbuseAddNew"></button></td>
						</tr>
						
						<!-- wkr20170531 -->
						<tr>
							<th colspan="3">Notes</th>
						</tr>
						<tr>
							<td colspan="3">
								<textarea data-bind="value: Assessment.SubstanceAbuseNotes"></textarea>
							</td>
						</tr>						
						
					</tfoot>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.SubstanceAbuseSources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.SubstanceAbuseSources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.SubstanceAbuseSources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.SubstanceAbuseSources.DisplaySet, enable: Assessment.SubstanceAbuseSources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.SubstanceAbuseSources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.SubstanceAbuseSources.SourcesAvailable(), value: Assessment.SubstanceAbuseSources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.SubstanceAbuseSources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-vocational-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Vocational History</span>
								<span class="section-subtitle" data-bind="style: { color: Assessment.VocationalHistoryAge() ? 'red' : '' }">(For ages 14 and older; vocational aptitude and interest evaluation, previous employment and acquired vocational skills, activities and interests)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.VocationalHistoryAge()">
							<td>Client is not old enough for this section</td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.VocationalHistory"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.VocationalHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.VocationalHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.VocationalHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.VocationalHistorySources.DisplaySet, enable: Assessment.VocationalHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.VocationalHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.VocationalHistorySources.SourcesAvailable(), value: Assessment.VocationalHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.VocationalHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-legal-dependency-history" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Legal & Dependency History</span>
								<span class="section-subtitle">(Include any criminal history, custody issues and child welfare involvement/case plan permanency goal)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.LegalDependencyHistory"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="sourcesLink">
					<table>
						<thead>
							<tr>
								<th colspan="3">Source</th>
							</tr>
						</thead>
						<tbody data-bind="foreach: Assessment.LegalDependencyHistorySources.Sources">
							<tr>
								<td data-bind="text: Type"></td>
								<td style="width: 10ex;" data-bind="text: Date"></td>
								<td style="width: 1%;"><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.LegalDependencyHistorySources.Remove"></button></td>
							</tr>
						</tbody>
						<tfoot>
							<tr data-bind="visible: !Assessment.LegalDependencyHistorySources.Display()">
								<td colspan="3" class="onlyButton"><button class="ico-plus" title="Link to Source" data-bind="click: Assessment.LegalDependencyHistorySources.DisplaySet, enable: Assessment.LegalDependencyHistorySources.SourcesAvailable().length > 0"></button></td>
							</tr>
							<tr data-bind="visible: Assessment.LegalDependencyHistorySources.Display()">
								<td colspan="2"><select data-bind="options: Assessment.LegalDependencyHistorySources.SourcesAvailable(), value: Assessment.LegalDependencyHistorySources.Selected, optionsText: 'OptionsText', optionsCaption: 'Select Source...'"></select></td>
								<td style="width: 1%;"><button class="ico-link" title="Link to Source" data-bind="click: Assessment.LegalDependencyHistorySources.Add"></button></td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
			<div id="section-significant-relationships" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Significant Relationships</span>
								<span class="section-subtitle">(Include skills that help maintain relationship with family, friends and any other significant relationships from client/family perspective)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.SignificantRelationships"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-potential-strengths" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Current and Potential Strengths</span>
								<span class="section-subtitle">(Include strengths from client/family perspective)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Client reports strengths are
								<textarea data-bind="value: Assessment.PotentialStrengths.Client"></textarea>
							</td>
						</tr>
						<tr>
							<td>
								Parents report client strengths are
								<textarea data-bind="value: Assessment.PotentialStrengths.Parent"></textarea>
							</td>
						</tr>
						<tr>
							<td>
								Family strengths are
								<textarea data-bind="value: Assessment.PotentialStrengths.Family"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-resources-available" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Resources Available</span>
								<span class="section-subtitle">(include what is available to client through natural support systems, basic needs, financial resources, health care,  etc)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<textarea data-bind="value: Assessment.ResourcesAvailable"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-safety-assessment" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Safety Assessment</span>
								<span class="section-subtitle">(Indicate any risk factors for this client , including personal/interpersonal factors and physical home environment. If there are identified risk factors, the current safety or risk management plan must be included)</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind="foreach: Assessment.Safety.Types" style="column-count: 2; -moz-column-count: 2; -webkit-column-count: 2;">
								<div>
									<input type="checkbox" data-bind="attr: { id: 'st_' + $index() }, checked: Selected">
									<label data-bind="attr: { for: 'st_' + $index() }, text: Type().Label">
									</label>
								</div>
							</td>
						</tr>
					</tbody>
					<tbody>
						<tr>
							<td>
								Other
								<textarea data-bind="value: Assessment.Safety.Other"></textarea>
							</td>
						</tr>
						<tr>
							<td>
								Brief description of risk factors above
								<textarea data-bind="value: Assessment.Safety.Description"></textarea>
							</td>
						</tr>
						<tr>
							<td>
								Safety/Risk Plan
								<textarea data-bind="value: Assessment.Safety.Plan"></textarea>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-current-services" class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="6">
								<span class="section-title">Current Services</span>
								<span class="section-subtitle">(Include all current services being provided and effectiveness)</span>
							</th>
						</tr>
						<tr data-bind="visible: Assessment.CurrentServicesActive().length > 0">
							<th>Agency/Provider</th>
							<th>Date Service Began</th>
							<th colspan="2">Service</th>
							<th>Effectiveness</th>
							<th style="width: 1%;"></th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.CurrentServices">
						<tr>
							<td><input type="text" data-bind="value: Provider" /></td>
							<td><input type="text" data-bind="value: DateBegin" /></td>
							<td><div data-bind="visible: Type() !== '0'"><select data-bind="options: $root.CurrentServicesTypes, value: Type, optionsValue: 'Id', optionsText: 'Label', optionsCaption: 'Choose...'"></select></div><div data-bind="visible: Type() === '0'"><input type="text" data-bind="value: TypeOther" /></div></td>
							<td><button class="ico-pencil" title="Switch Edit Mode" data-bind="click: TypeToggle"></button></td>
							<td><input type="text" data-bind="value: Effectiveness" /></td>
							<td><button class="ico-minus" title="Remove" data-bind="click: $root.Assessment.CurrentServicesRemove"></button></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="6" class="onlyButton"><button class="ico-plus" title="Add Service" data-bind="click: Assessment.CurrentServicesAddNew"></button></td>
						</tr>
					</tfoot>
				</table>
			</div>
			<div id="section-functional-assessment" class="form-section">
				<table class="center">
					<thead>
						<tr>
							<th>Functional Assessment</th>
							<th>Fully functioning; no current service needs</th>
							<th>Partial functioning; some service needs</th>
							<th>Low functioning; immediate service needs</th>
							<th>Client/Family has ability & willingness to address this goal</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Functional">
						<tr>
							<th>
								<span class="section-title" data-bind="text: Type().Label"></span>
								<span class="section-subtitle" data-bind="text: Type().Description"></span>
							</th>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="no"></td>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="some"></td>
							<td><input type="radio" data-bind="checked: ServiceNeeds, attr: { name: Type.ControlName } " value="immediate"></td>
							<td><input type="checkbox" data-bind="checked: Willingness, enable: (ServiceNeeds() === 'some' || ServiceNeeds() === 'immediate')" value='true'></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="section-service-needs-recommendations" class="form-section">
				<table>
					<thead>
						<tr>
							<th>
								<span class="section-title">Needs and Recommendations</span>
							</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: Assessment.Functional">
						<!-- ko if: Willingness -->
						<tr>
							<td>
								<span class="subsection-title" data-bind="text: Type().Label"></span>
							</td>
						</tr>
						<tr>
							<td>Needs</td>
						</tr>
						<tr>
							<td>
								<textarea data-bind='value: NeedSummary'></textarea>
							</td>
						</tr>
						<tr>
							<td>Recommended TCM Activities</td>
						</tr>
						<tr>
							<td>
								<textarea data-bind='value: ActivityRecommendations'></textarea>
							</td>
						</tr>
						<!-- /ko -->
					</tbody>
				</table>
			</div>
		</div>
	</body>
</html>
